[package]
name = "generate-test-gateway-txn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helium-crypto = "0.7.0"
hex = "0.4.3"
helium-proto = { git = "https://github.com/helium/proto", branch="master"}
base64 = "0.21.2"

