[package]
name = "lazy-distributor"
version = "0.0.1"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lazy_distributor"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[profile.release]
overflow-checks = true

[dependencies]
anchor-lang = { version = "0.25.0", features = ["init-if-needed"] }
anchor-spl = "0.25.0"
mpl-token-metadata = { version = "1.3.4", features = ["no-entrypoint"] }
mpl-bubblegum = {path = "../../deps/metaplex-program-library/bubblegum/program", features = ["cpi"] }
circuit-breaker = { path = "../circuit-breaker", features = ["cpi"] }
shared-utils = { path = "../shared-utils" }
spl-account-compression = { version="0.1.3", features = ["cpi"] }